[adconfig_dev]
# IP for the app 3D or DFO
ADAPP_SERVER = localhost
# Port for the app 3D or DFO
ADAPP_PORT = 8088
REPEATER_IP = 192.168.10.115
REPEATER_PORT = 5900
ADAPP_TOKENVALIDATION_URL = /system/webdev/novnc_dev/vnc/json_validation

[adconfig_prod]
adpapp_ip = 192.168.10.115
adpapp_port = 80
repeater_ip = 192.168.10.115
repeater_port = 5900
url_token = "/ahm/cms_validation.json"
ADAPP_SERVER = "localhost"
# ADAPP_PORT = 5000
# ADAPP_TOKENVALIDATION_URL = "/ahm/cms_validation.json"
ADAPP_PORT = 8088
ADAPP_TOKENVALIDATION_URL = "/system/webdev/novnc_dev/vnc/json_validation"

[adconfig_3dapp]
adpapp_ip = 192.168.10.115
adpapp_port = 80
repeater_ip = 192.168.10.115
repeater_port = 5900
url_token = "/ahm/cms_validation.json"
ADAPP_SERVER = "localhost"
# ADAPP_PORT = 5000
# ADAPP_TOKENVALIDATION_URL = "/ahm/cms_validation.json"
ADAPP_PORT = 8088
ADAPP_TOKENVALIDATION_URL = /system/webdev/novnc_dev/vnc/json_validation

[local]
# IP for the app 3D or DFO
ADAPP_SERVER = localhost
# Port for the app 3D or DFO
ADAPP_PORT = 8088
REPEATER_IP = 192.168.10.115
REPEATER_PORT = 5900
ADAPP_TOKENVALIDATION_URL = /main/system/webdev/uvnc_Dev/dev/token_validation